apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-secret
  namespace: medplatform
type: Opaque
stringData:
  # Reemplaza con tu clave real de SendGrid (o deja el placeholder para demo)
  SENDGRID_API_KEY: "SG.placeholder"
