apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: medplatform-data
type: Opaque
stringData:
  username: postgres
  password: postgrespassword
---
# Copia del secret en el namespace de la app (los pods no pueden referenciar secrets de otro namespace)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: medplatform
type: Opaque
stringData:
  username: postgres
  password: postgrespassword
