apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-appointment
  namespace: medplatform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-appointment
  template:
    metadata:
      labels:
        app: ms-appointment
        version: v1
    spec:
      containers:
      - name: ms-appointment
        image: medplatform/ms-appointment:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: medplatform-config
              key: DATABASE_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: medplatform-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: ROOT_PATH
          value: "/appointment"
        readinessProbe:
          httpGet:
            path: /docs
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /docs
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ms-appointment
  namespace: medplatform
spec:
  selector:
    app: ms-appointment
  ports:
  - name: http
    port: 3003
    targetPort: 3003
